# Generated by Django 2.2 on 2022-12-23 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['title'], 'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
    ]
